### ISSUE TITLE
[Quick discussion] a:link and a:visited colors

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#11]
Our default `dodgerblue` color on codebuddies.org is not very accessible against a white background (or with white font against its blue); we need to select a slightly darker blue for our links.

**Comment by lpatmo** [comment]
These definitions can probably be put into the `App.css` file.

**Comment by peoray** [comment]
I'll pick this up :)

**Comment by lpatmo** [comment]
@peoray If you have suggestions for the hex color of links, feel free to share here. :)

**Comment by peoray** [comment]
@lpatmo, I have a couple I have found so far:
- #00008b
- #6807f9
- #3e64ff
- #003366

Also, this link has some variants, if you can take a look and see if you like anyone
[Color hexa](https://www.colorhexa.com/00008b)

**Comment by lpatmo** [comment]
@peoray Thank you! Let's go with `#00008b` for now. :)

**Comment by peoray** [comment]
How does this get applied? Your suggestion of using `App.css` is vague. Can you be more elaborate please :)

**Comment by lpatmo** [comment]
@peoray I was thinking you'd add `a:link` and `a:visited` styles to the `App.css` file so that they'd be global. Just realized we didn't actually come up with a color for a:visited yet... maybe `#6807f9` for a:visited?

**Comment by peoray** [comment]
Alright, will do :)
