### ISSUE TITLE
[Feature] Personal Menu component

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#13]
We need to create a new "Personal Menu" component that displays the following (see left side of mockup):

![image](https://user-images.githubusercontent.com/4512699/67184332-6402e280-f398-11e9-902c-ac13c571a0d7.png)

None of this needs to "work" right now, but we could follow the UI from https://codesandbox.io/s/ujp8m, which is documented at https://material-ui.com/components/tree-view/.

**Comment by thesanjeevsharma** [comment]
Hello, I would like to work on this issue!

**Comment by lpatmo** [comment]
@thesanjeevsharma Thanks! This repo is kinda bare-bones right now, but let me know if you have any questions. We're using `material-ui` and this component simply needs to be something that could be included in a bunch of different pages.

**Comment by lpatmo** [comment]
(Closing, since we have a `PersonalMenu` component now!)
