### ISSUE TITLE
[UI] Create "user icon" menu component in nav

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#14]
We'll need some sort of user icon component that looks like the thing on the far right:

![image](https://user-images.githubusercontent.com/4512699/67184924-a547c200-f399-11e9-8fa1-aaf7dd382fc6.png)

When this avatar is clicked on, it should open up a "Log out" link.

Example we can follow: https://codesandbox.io/s/v4v97

We'll have to use a material-ui icon for the user avatar/icon.

**Comment by rozenraymond** [comment]
Hi, I'm happy to take this issue. However, the sandbox link is not working for me. Can you please share another sandbox link? Cheers!

**Comment by lpatmo** [comment]
@rozenraymond Thanks! And sorry about the link! Here it is: https://codesandbox.io/s/v4v97. It comes from the material-ui docs at https://material-ui.com/components/menus/

**Comment by quaj** [comment]
does it need background color?

**Comment by lpatmo** [comment]
@quaj Yeah, was thinking we'd use material-ui for the dropdown. And no particular requirement for a background color. But @rozenraymond has already a PR for this. Thanks for your question though!
