### ISSUE TITLE
Create JSON folder/files to mock data returned by API calls

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#15]
We'll need to mock some JSON data that we can work with until we've made a decision on using github.com/codebuddies/serverless (graphQL and Apollo Client) or github.com/codebuddies/django-conceept (Django REST Framework - traditional API endpoints, probably without GraphQL, since according to https://yeti.co/blog/migrating-from-rest-to-graphql-in-django/, graphene has performance issues that need to be dealt with still.)

**Comment by lpatmo** [comment]
Note: https://docs.google.com/document/d/1y0AkJVHdONGsWQGgIrM31007U0wf1fJNxiu5hDrt7PE/edit#heading=h.9rfl8wc4fp2x by @BethanyG (scroll down to see the most recent diagram) is a good reference point for this data.

**Comment by jonnyfluckey** [comment]
I would be happy to help out with this request. I just will need access to the document in the comments in order to assist and know what data I am putting in the JSON file

**Comment by lpatmo** [comment]
Huh, the doc should be accessible! (I was able to open it up in an incognito browser.) If not, here is a screenshot of sample datat we need most right now (Resources): 

![image](https://user-images.githubusercontent.com/4512699/67223109-84a45a00-f3e3-11e9-9e2b-41242f948171.png)

**Comment by BethanyG** [comment]
Hi @jonnyfluckey,

The easiest might be to just have me give you the JSON that DRF produces, and you can adapt from there.  I will post it in the next few minutes.  There is also a version from when @billglover first mocked the API.  Let me see if I can find it for you.

**Comment by BethanyG** [comment]
@jonnyfluckey @lpatmo 

Here is the link for the Swagger mock that @billglover  did.  https://app.swaggerhub.com/apis-docs/billglover/CodeBuddies/0.0.1

**Comment by jonnyfluckey** [comment]
Thank you @BethanyG ! I will work on this today, and ask for feedback/advice as needed :)

**Comment by BethanyG** [comment]
@jonnyfluckey,

So you'll have to break this down for your various needs and formats, but here is a (very!) rough list of mocked data from the DRF implementation we've worked on (apologies - I had to save it as txt..but if you paste it into a code editor, it's valid JSON).
[mocked_api_data.txt](https://github.com/codebuddies/react-concept/files/3752059/mocked_api_data.txt)
.  Let me know if you have questions or issues.

-B

**Comment by lpatmo** [comment]
> give you the JSON that DRF produces
> push my fixtures for the Django project today

Sounds great! Thanks @BethanyG!
