### ISSUE TITLE
Set up Resources "submit" page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#16]
See: 
![image](https://user-images.githubusercontent.com/4512699/67186822-b692cd80-f39d-11e9-8646-975c835e466e.png)

Notes:
- use material-ui's `Grid` component to create a two-column structure for the page
- ignore the "personal menu" component on the left
- Create a form that has the inputs indicated above
- Add an additional `tags` UI component to the form (h/t @grimmothy) that is missing from the mockup above
- Don't worry about completing the `onSubmit` functionality for now, though there should be `onChange` and `onSubmit` handlers

**Comment by mazma1** [comment]
@lpatmo I'll be happy to help with this

**Comment by lpatmo** [comment]
@mazma1 Thank you! I've marked this as claimed. Let me know if you need any help, or change your mind about working on this.

**Comment by mazma1** [comment]
Noted @lpatmo, I'll get to work soon!

**Comment by mazma1** [comment]
Hi @lpatmo, I'm close to wrapping this up. Do you have any preferred package I can use for the `tags` UI component?

**Comment by lpatmo** [comment]
@mazma1 Sorry for the slow reply! I was thinking of https://material-ui.com/components/chips/ for the tags component. :) Thank you for the PR -- will review tomorrow!

**Comment by havenchyk** [comment]
@lpatmo can be closed
