### ISSUE TITLE
Set up "Search" React component

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#17]
We need a `Search` component that takes in data as props and returns results as children. 

For the UI, we can use the `Input` component from material-ui (https://material-ui.com/api/input/#main-content), and specify it as `type="search"`. 

Thoughts: 
- <Search data={data}>{children}</Search> (something like that) 
- should be a functional component
- When we use this component, replace {children} with 
- First use of this component will be with Resources. We need #15 to be addressed before we have mock data, but once we have it we can search on resource title.

**Comment by timi-codes** [comment]
I would love to take this up

**Comment by timi-codes** [comment]
I think you need to share more light into what is required. Some of the description above appears broken.

**Comment by lpatmo** [comment]
@timi-codes Thanks, I'll update the specs! Sorry they were a little vague. :) A couple of open PRs from last night have been merged in, so we now have sample `resource` data that the React component should be able to search through. Let me set up a boilerplate for you; will follow up.

**Comment by lpatmo** [comment]
@timi-codes I merged this in:

![image](https://user-images.githubusercontent.com/4512699/67264954-5bc2aa00-f461-11e9-87db-4cbc6a4cc9d7.png)

Ideally, the behavior should be:
- when a user starts typing, we filter based on the resource title or description using a `filter` method.

Can discuss more implementation details tomorrow if you'd like!

**Comment by timi-codes** [comment]
Thanks for the update @ipatmo . I will look at what has been done and continue my implementation of the Search functionality.

**Comment by lpatmo** [comment]
Re: implementation -- we'll need to write a `search` function that filters data based on either the `title` or `description`. Then we'll need to update a `searchResults` state and have the output of resources on the screen reflect whatever is in `searchResults`.

**Comment by lpatmo** [comment]
Update: closing this in favor of #4
