### ISSUE TITLE
[React] Refactor `handleExpandClick` to open up one card at a time

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#26]
See: https://cb-react-concept.netlify.com/resources

Right now, clicking on "toggle" opens up every card. We need to open up one at a time.

**Comment by rozenraymond** [comment]
I'm happy to work on this too 👍

**Comment by lpatmo** [comment]
@rozenraymond I'll mark this as claimed. Let me know if you need help, or change your mind about working on this issue. Thanks!

**Comment by havenchyk** [comment]
can be closed :)
