### ISSUE TITLE
[CSS] Style auto-expanding textarea

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#27]
Material-UI gives us an auto-resizing textarea (https://material-ui.com/components/textarea-autosize/) which we use in Resources/index.js, but it's not really styled.

Task: polish it up to look less like a raw form element.

Docs for adding CSS using material-ui: https://material-ui.com/styles/basics/

**Comment by Dan2D** [comment]
I can take a shot at this.

**Comment by Dan2D** [comment]
Okay, so I just updated the useStyles in the Resources index.js to make it a base styling more or less like the normal material-ui text box as you can see below.

![image](https://user-images.githubusercontent.com/32251318/67298781-95ff6c00-f4a0-11e9-97de-f69e3d0fb6a2.png)

Let me know if it's good to go and I'll submit the PR

**Comment by lpatmo** [comment]
@Dan2D That looks great! Feel free to submit the PR. Thanks!

**Comment by havenchyk** [comment]
seems can be closed :)
