### ISSUE TITLE
Set up skeleton for Hangouts page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#32]
Set up a skeleton for a hangouts page, with a calendar view and list of hangout proposals.

**Comment by lpatmo** [comment]
I'm kind of eager to take a stab at this to test out some UI assumptions :)

**Comment by helenzhao093** [comment]
@lpatmo let me know if i can help out

**Comment by lpatmo** [comment]
Closing this issue based on some new UI thinking... specifically that hangouts could be proposed _for_ a resource, _for_ a project, _for_ a group, etc.

![image](https://user-images.githubusercontent.com/4512699/73604350-3f480a80-4544-11ea-88c4-8884be3e795c.png)

Will open a new issue when the specs are more clearly defined!
