### ISSUE TITLE
Fix link to /resources on "submit resource" page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#41]
Not sure if we're missing an import of react-router-dom or something, but the link at https://cb-react-concept.netlify.com/submit-resource appears broken.

Guessing this'll be a relatively straightforward fix, but haven't dug into this closely.

**Comment by havenchyk** [comment]
Let me try to fix it @lpatmo

**Comment by havenchyk** [comment]
@lpatmo seems everything working smooth, could you please clarify, which link at which page is broken?

**Comment by havenchyk** [comment]
@lpatmo https://github.com/codebuddies/react-concept/pull/42
