### ISSUE TITLE
Add GitHub Issue and PR Templates

### ISSUE THREAD

**Issue by wuworkshop** [codebuddies/react-concept#43]
Judging from some of the PRs that have been received so far, this repo could really use a PR template. An issue template would also be nice to have.

The PR template should be easy for the contributor to fill out and make use of GitHub keywords for closing issues.

See this GitHub Help article for the keywords:
https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

See these PR templates as examples:
https://github.com/thepracticaldev/dev.to/blob/master/.github/PULL_REQUEST_TEMPLATE.md

https://github.com/NativeScript/docs/blob/master/.github/pull_request_template.md

---

Might be good to have 2 issue templates:
1. For feature requests.
2. For bug reports.

See dev.to's examples here:
https://github.com/thepracticaldev/dev.to/tree/master/.github/ISSUE_TEMPLATE

**Comment by nehayward** [comment]
I'll get started on this.

**Comment by nehayward** [comment]
Any idea on what you'd like for copy write

**Comment by lpatmo** [comment]
@wuworkshop Thanks for filing this issue!
