### ISSUE TITLE
[React] Create a /coworking route 

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/react-concept#46]
At the moment, the 24/7 coworking space link leads nowhere: 

![image](https://user-images.githubusercontent.com/4512699/67840541-598ccb00-fab3-11e9-99d2-0ba762b8bc68.png)

Requirements:
- Create a /coworking route that renders a new <Coworking /> component
- Keep the personal menu appearing on the left
- On this new page, show three options: 1/ 24/7 speaking-OK hangout; 2/ 24/7 silent hangout; 3/ a space to load in a `<Discussion>` component (as described in #45) that'll let users chat and propose new (probably private) hangouts from there

No real mockups for this (sorry), but here's an initial idea:

![image](https://user-images.githubusercontent.com/4512699/67840853-08c9a200-fab4-11e9-94de-769c61723af9.png)

**Comment by havenchyk** [comment]
@lpatmo could you please clarify what are two blocks on the left, what will be placed there in the future?

**Comment by lpatmo** [comment]
@havenchyk Thanks for asking! Am thinking each block on the left would have a "Join room" button, which when clicked on would open up a meet.jitsi.com iframe (or Zoom hangout, if we decide to pay for the Zoom API in the future). 

This page is basically the second iteration of https://codebuddies.org/coworking, which has description text we can re-use. :) 

The main difference is that instead of offering one "silent" hangout, we'd have two rooms -- one where talking is allowed, and one where the idea is that folks would just screenshare as they're studyinig/working on projects, for the company.
