### ISSUE TITLE
Please help and add prettierrc

### ISSUE THREAD

**Issue by jesperhodge** [codebuddies/react-concept#78]
I have a problem because you are using prettier in this project, but there is no explicit prettier config file right now. That means that my formatting will default to my default system prettier config, which is very different (I don't use semicolons in other projects for example!). That really keeps me from being able to submitting any code right now. Can you please fix this?

**Comment by angelocordon** [comment]
Thanks @jesperhodge! Good call out, will check it out.

**Comment by lpatmo** [comment]
Oops, sorry about that -- thanks for looking into this, Angelo!
